package director

// Director is a small runtime for already-compiled entity/world-model rules.
//
// The package intentionally does not parse author-facing rule strings. A GAMS-side
// compiler is expected to turn names such as `PLAYER.current_location=ROOM` and
// rule syntax such as `ON: *.item` into this package's typed IR. The game then
// initializes State from Director_Data, sends Trigger values, and observes the
// Result plus mutated world model state.
//
// Typical use:
//
//     state := director.init(compiled_director_data)
//     defer director.destroy(&state)
//
//     result := director.trigger(&state, director.Trigger{kind = .Signal, signal = START})
//     if result.matched {
//         // Use result.rule/result.changes for game-side sys_director behavior.
//     }
//
// Runtime ids are separate from authored/debug strings. Generated Odin constants
// should give meaningful names to Entity_Id, Word_Id, and Rule_Id values.

// Entity_Id identifies an authored entity in compiled Director data.
Entity_Id :: distinct u32

// Word_Id identifies an authored word/property/tag/signal in compiled Director data.
Word_Id :: distinct u32

// Rule_Id identifies an authored rule in compiled Director data.
Rule_Id :: distinct u32

INVALID_ENTITY :: Entity_Id(0xffffffff)
INVALID_WORD :: Word_Id(0xffffffff)
INVALID_RULE :: Rule_Id(0xffffffff)

// Range references a contiguous slice inside one of Director_Data's flat IR pools.
Range :: struct {
	offset: u32,
	count:  u32,
}

// Selector_Kind describes the subject of a Matcher.
Selector_Kind :: enum u8 {
	Entity, // Match one compiled entity id.
	Any, // Match any entity in State.
	Trigger, // Match the triggering entity.
}

// Selector is the compiled equivalent of an Elm matcher prefix: `ID`, `*`, or `$`.
Selector :: struct {
	kind:   Selector_Kind,
	entity: Entity_Id,
}

Compare_Op :: enum u8 {
	Eq,
	Gt,
	Lt,
}

Query_Kind :: enum u8 {
	Has_Tag,
	Has_Stat,
	Has_Link,
	Not,
}

Stat_Value_Kind :: enum u8 {
	Immediate,
	From_Entity_Stat,
	From_Trigger_Stat,
}

Stat_Value :: struct {
	kind:   Stat_Value_Kind,
	entity: Entity_Id,
	key:    Word_Id,
	value:  i32,
}

Link_Value_Kind :: enum u8 {
	Specific_Matcher,
	From_Entity_Link,
	From_Trigger_Link,
}

Link_Value :: struct {
	kind:          Link_Value_Kind,
	matcher_index: u32,
	entity:        Entity_Id,
	key:           Word_Id,
}

// Query is one compiled entity predicate.
//
// Examples from source syntax:
// - `.item` compiles to Has_Tag.
// - `.level>2` compiles to Has_Stat.
// - `.location=(*.dark)` compiles to Has_Link with a nested matcher.
// - `.!locked` compiles to Not pointing at another Query.
Query :: struct {
	kind:       Query_Kind,
	key:        Word_Id,
	op:         Compare_Op,
	stat_value: Stat_Value,
	link_value: Link_Value,
	nested:     u32,
}

// Matcher is the compiled equivalent of an entity matcher/query expression.
//
// Examples from source syntax:
// - `PLAYER`
// - `*.item.!fixed`
// - `PLAYER.location=(*.dark)`
Matcher :: struct {
	selector: Selector,
	queries:  Range,
}

Change_Kind :: enum u8 {
	Add_Tag,
	Remove_Tag,
	Set_Stat,
	Inc_Stat,
	Dec_Stat,
	Set_Link,
	Remove_Link,
	Add_Entity,
	Remove_Entity,
	Remove_Property,
}

Change_Target_Kind :: enum u8 {
	Entity,
	Trigger,
	All_Matching,
}

Change_Target :: struct {
	kind:          Change_Target_Kind,
	entity:        Entity_Id,
	matcher_index: u32,
}

Link_Target_Kind :: enum u8 {
	Entity,
	Trigger,
	Lookup_Entity_Link,
	Lookup_Trigger_Link,
}

Link_Target :: struct {
	kind:   Link_Target_Kind,
	entity: Entity_Id,
	key:    Word_Id,
}

Change :: struct {
	target:      Change_Target,
	kind:        Change_Kind,
	key:         Word_Id,
	int_value:   i32,
	link_target: Link_Target,
}

Rule_Trigger_Kind :: enum u8 {
	Signal,
	Entity_Matcher,
}

Rule_Trigger :: struct {
	kind:          Rule_Trigger_Kind,
	signal:        Word_Id,
	matcher_index: u32,
}

// Rule is one compiled rule. The compiler should precompute weight so runtime
// matching can choose the most specific rule without re-deriving authoring syntax.
Rule :: struct {
	id:         Rule_Id,
	trigger:    Rule_Trigger,
	conditions: Range,
	changes:    Range,
	weight:     i32,
}

Stat :: struct {
	key:   Word_Id,
	value: i32,
}

Link :: struct {
	key:    Word_Id,
	target: Entity_Id,
}

Entity_Def :: struct {
	id:      Entity_Id,
	tags:    []Word_Id,
	stats:   []Stat,
	links:   []Link,
	removed: bool,
}

// Director_Data is immutable compiled data generated by GAMS or by a generated
// Odin fixture. The runtime borrows these slices; it does not own or free them.
Director_Data :: struct {
	entities: []Entity_Def,
	rules:    []Rule,
	matchers: []Matcher,
	queries:  []Query,
	changes:  []Change,
}

Entity_State :: struct {
	id:      Entity_Id,
	tags:    [dynamic]Word_Id,
	stats:   [dynamic]Stat,
	links:   [dynamic]Link,
	removed: bool,
}

// State is the mutable Director world model initialized from Director_Data.
// Game code should treat fields as read-only and use package procedures to query
// or advance state.
State :: struct {
	// Store the immutable data value so State does not borrow a pointer to a
	// caller's stack variable. Its slices still reference their backing storage.
	data:     Director_Data,
	entities: [dynamic]Entity_State,
	changes:  [dynamic]Applied_Change,
}

Trigger_Kind :: enum u8 {
	Entity,
	Signal,
}

// Trigger is a runtime event sent by game-specific code such as sys_director.
// Entity triggers correspond to interactions with authored entities. Signal
// triggers correspond to programmatic events such as `start`, `wait`, or room hooks.
Trigger :: struct {
	kind:   Trigger_Kind,
	entity: Entity_Id,
	signal: Word_Id,
}

// Applied_Change describes one concrete property or availability mutation
// produced while applying a rule. Matcher targets are resolved, so entity is
// always the id that actually changed. Only effective mutations are reported; idempotent
// writes and removals of absent properties produce no entry.
Applied_Change_Kind :: enum u8 {
	Tag_Added,
	Tag_Removed,
	Stat_Set,
	Stat_Removed,
	Link_Set,
	Link_Removed,
	Entity_Added,
	Entity_Removed,
}

Applied_Change :: struct {
	kind:        Applied_Change_Kind,
	entity:      Entity_Id,
	key:         Word_Id,
	stat_before: i32,
	stat_after:  i32,
	link_before: Entity_Id,
	link_after:  Entity_Id,
}

// Result reports the rule selected by trigger. If matched is false, rule is
// INVALID_RULE and changes is empty. changes borrows State scratch storage and
// remains valid only until the next trigger call or destroy.
Result :: struct {
	rule:    Rule_Id,
	matched: bool,
	changes: []Applied_Change,
}

// init creates mutable runtime State from immutable compiled Director_Data.
@(require_results)
init :: proc(data: Director_Data) -> State {
	state := State {
		data = data,
	}
	for def in data.entities {
		assert(int(def.id) == len(state.entities))
		entity := Entity_State {
			id      = def.id,
			removed = def.removed,
		}
		for tag in def.tags {
			append(&entity.tags, tag)
		}
		for stat in def.stats {
			append(&entity.stats, stat)
		}
		for link in def.links {
			append(&entity.links, link)
		}
		append(&state.entities, entity)
	}
	return state
}

// destroy releases memory owned by State. It does not release Director_Data.
destroy :: proc(state: ^State) {
	for &entity in state.entities {
		delete(entity.tags)
		delete(entity.stats)
		delete(entity.links)
	}
	delete(state.entities)
	delete(state.changes)
	state^ = {}
}

// trigger finds the best matching rule for event, applies its compiled changes,
// and returns the selected rule plus the concrete property mutations it made.
@(require_results)
trigger :: proc(state: ^State, event: Trigger) -> Result {
	clear(&state.changes)
	rule_index, ok := find_matching_rule(state, event)
	if !ok {
		return Result{rule = INVALID_RULE, matched = false, changes = state.changes[:]}
	}
	rule := &state.data.rules[rule_index]
	apply_rule(state, rule_index, event)
	return Result{rule = rule.id, matched = true, changes = state.changes[:]}
}

// find_matching_rule returns the index into Director_Data.rules for event without
// applying changes. Use trigger for normal game flow.
@(require_results)
find_matching_rule :: proc(state: ^State, event: Trigger) -> (u32, bool) {
	best_index: u32
	best_weight: i32
	found := false
	for &rule, index in state.data.rules {
		if !rule_trigger_matches(state, &rule, event) {
			continue
		}
		if !conditions_match(state, &rule, event) {
			continue
		}
		if !found || rule.weight > best_weight {
			found = true
			best_index = u32(index)
			best_weight = rule.weight
		}
	}
	return best_index, found
}

// apply_rule applies a previously selected rule by Director_Data.rules index.
// This is primarily useful when game code wants to inspect the selected rule
// before committing its changes.
apply_rule :: proc(state: ^State, rule_index: u32, event: Trigger) {
	assert(int(rule_index) < len(state.data.rules))
	rule := &state.data.rules[rule_index]
	for change_index in int(rule.changes.offset) ..< int(rule.changes.offset + rule.changes.count) {
		apply_change(state, &state.data.changes[change_index], event)
	}
}

// query appends all entities matching Director_Data.matchers[matcher_index] to out.
// The caller owns out and may reuse it across calls.
query :: proc(state: ^State, matcher_index: u32, event: Trigger, out: ^[dynamic]Entity_Id) {
	assert(int(matcher_index) < len(state.data.matchers))
	matcher := &state.data.matchers[matcher_index]
	#partial switch matcher.selector.kind {
	case .Entity:
		if entity_is_active(state, matcher.selector.entity) &&
		   entity_matches_matcher(state, matcher, matcher.selector.entity, event) {
			append(out, matcher.selector.entity)
		}
	case .Trigger:
		if event.kind == .Entity &&
		   entity_is_active(state, event.entity) &&
		   entity_matches_matcher(state, matcher, event.entity, event) {
			append(out, event.entity)
		}
	case .Any:
		for &entity in state.entities {
			if !entity.removed && entity_matches_matcher(state, matcher, entity.id, event) {
				append(out, entity.id)
			}
		}
	}
}

// entity_has_tag reports whether an entity currently has a tag.
@(require_results)
entity_has_tag :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) -> bool {
	assert(valid_entity(state, entity_id))
	return has_tag(&state.entities[int(entity_id)], key)
}

// entity_add_tag adds a tag to mutable runtime state.
entity_add_tag :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) {
	assert(valid_entity(state, entity_id))
	add_tag(&state.entities[int(entity_id)], key)
}

// entity_remove_tag removes a tag from mutable runtime state.
entity_remove_tag :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) {
	assert(valid_entity(state, entity_id))
	remove_tag(&state.entities[int(entity_id)], key)
}

// entity_stat returns an entity stat. Missing stats are treated as 0, matching
// Elm Narrative Engine semantics.
@(require_results)
entity_stat :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) -> i32 {
	assert(valid_entity(state, entity_id))
	return get_stat_value(&state.entities[int(entity_id)], key)
}

// entity_set_stat updates or dynamically adds a stat to mutable runtime state.
// It does not modify the immutable compiled Director_Data.
entity_set_stat :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id, value: i32) {
	assert(valid_entity(state, entity_id))
	set_stat(&state.entities[int(entity_id)], key, value)
}

// entity_remove_stat removes a dynamically managed stat from mutable runtime state.
entity_remove_stat :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) {
	assert(valid_entity(state, entity_id))
	remove_stat(&state.entities[int(entity_id)], key)
}

// entity_link returns an entity link target, or false when the link is absent.
@(require_results)
entity_link :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) -> (Entity_Id, bool) {
	assert(valid_entity(state, entity_id))
	return get_link_target(&state.entities[int(entity_id)], key)
}

// entity_set_link updates or dynamically adds a link to mutable runtime state.
entity_set_link :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id, target: Entity_Id) {
	assert(valid_entity(state, entity_id))
	assert(valid_entity(state, target))
	set_link(&state.entities[int(entity_id)], key, target)
}

// entity_remove_link removes a dynamically managed link from mutable runtime state.
entity_remove_link :: proc(state: ^State, entity_id: Entity_Id, key: Word_Id) {
	assert(valid_entity(state, entity_id))
	remove_link(&state.entities[int(entity_id)], key)
}

@(private = "file")
@(require_results)
rule_trigger_matches :: proc(state: ^State, rule: ^Rule, event: Trigger) -> bool {
	#partial switch rule.trigger.kind {
	case .Signal:
		return event.kind == .Signal && event.signal == rule.trigger.signal
	case .Entity_Matcher:
		if event.kind != .Entity {
			return false
		}
		assert(int(rule.trigger.matcher_index) < len(state.data.matchers))
		return entity_matches_link_matcher(
			state,
			&state.data.matchers[rule.trigger.matcher_index],
			event.entity,
			event,
		)
	}
	return false
}

@(private = "file")
@(require_results)
conditions_match :: proc(state: ^State, rule: ^Rule, event: Trigger) -> bool {
	for matcher_index in int(rule.conditions.offset) ..< int(rule.conditions.offset + rule.conditions.count) {
		assert(matcher_index < len(state.data.matchers))
		matches: [dynamic]Entity_Id
		query(state, u32(matcher_index), event, &matches)
		ok := len(matches) > 0
		delete(matches)
		if !ok {
			return false
		}
	}
	return true
}

@(private = "file")
@(require_results)
entity_matches_link_matcher :: proc(state: ^State, matcher: ^Matcher, entity_id: Entity_Id, event: Trigger) -> bool {
	if !entity_is_active(state, entity_id) {
		return false
	}
	#partial switch matcher.selector.kind {
	case .Entity:
		if entity_id != matcher.selector.entity {
			return false
		}
	case .Trigger:
		if event.kind != .Entity || entity_id != event.entity {
			return false
		}
	case .Any:
	}
	return entity_matches_queries(state, matcher.queries, entity_id, event)
}

@(private = "file")
@(require_results)
entity_matches_matcher :: proc(state: ^State, matcher: ^Matcher, entity_id: Entity_Id, event: Trigger) -> bool {
	if !entity_is_active(state, entity_id) {
		return false
	}
	#partial switch matcher.selector.kind {
	case .Entity:
		assert(entity_id == matcher.selector.entity)
	case .Trigger:
		assert(event.kind == .Entity && entity_id == event.entity)
	case .Any:
	}
	return entity_matches_queries(state, matcher.queries, entity_id, event)
}

@(private = "file")
@(require_results)
entity_matches_queries :: proc(state: ^State, queries: Range, entity_id: Entity_Id, event: Trigger) -> bool {
	if !valid_entity(state, entity_id) {
		return false
	}
	for query_index in int(queries.offset) ..< int(queries.offset + queries.count) {
		if !query_matches(state, u32(query_index), entity_id, event) {
			return false
		}
	}
	return true
}

@(private = "file")
@(require_results)
query_matches :: proc(state: ^State, query_index: u32, entity_id: Entity_Id, event: Trigger) -> bool {
	assert(int(query_index) < len(state.data.queries))
	q := &state.data.queries[query_index]
	entity := &state.entities[int(entity_id)]
	#partial switch q.kind {
	case .Has_Tag:
		return has_tag(entity, q.key)
	case .Has_Stat:
		actual := get_stat_value(entity, q.key)
		expected, ok := resolve_stat_value(state, q.stat_value, event)
		if !ok {
			return false
		}
		return compare_i32(actual, q.op, expected)
	case .Has_Link:
		actual, ok := get_link_target(entity, q.key)
		if !ok {
			return false
		}
		return resolve_link_match(state, actual, q.link_value, event)
	case .Not:
		return !query_matches(state, q.nested, entity_id, event)
	}
	return false
}

@(private = "file")
@(require_results)
resolve_stat_value :: proc(state: ^State, value: Stat_Value, event: Trigger) -> (i32, bool) {
	#partial switch value.kind {
	case .Immediate:
		return value.value, true
	case .From_Entity_Stat:
		if !valid_entity(state, value.entity) {
			return 0, false
		}
		return get_stat_value(&state.entities[int(value.entity)], value.key), true
	case .From_Trigger_Stat:
		if event.kind != .Entity {
			return 0, false
		}
		return get_stat_value(&state.entities[int(event.entity)], value.key), true
	}
	return 0, false
}

@(private = "file")
@(require_results)
resolve_link_match :: proc(state: ^State, actual: Entity_Id, value: Link_Value, event: Trigger) -> bool {
	if !valid_entity(state, actual) {
		return false
	}
	#partial switch value.kind {
	case .Specific_Matcher:
		assert(int(value.matcher_index) < len(state.data.matchers))
		return entity_matches_link_matcher(state, &state.data.matchers[value.matcher_index], actual, event)
	case .From_Entity_Link:
		if !valid_entity(state, value.entity) {
			return false
		}
		expected, ok := get_link_target(&state.entities[int(value.entity)], value.key)
		return ok && actual == expected
	case .From_Trigger_Link:
		if event.kind != .Entity {
			return false
		}
		expected, ok := get_link_target(&state.entities[int(event.entity)], value.key)
		return ok && actual == expected
	}
	return false
}

@(private = "file")
apply_change :: proc(state: ^State, change: ^Change, event: Trigger) {
	#partial switch change.target.kind {
	case .Entity:
		apply_change_to_entity(state, change.target.entity, change, event)
	case .Trigger:
		if event.kind == .Entity {
			apply_change_to_entity(state, event.entity, change, event)
		}
	case .All_Matching:
		matches: [dynamic]Entity_Id
		query(state, change.target.matcher_index, event, &matches)
		for entity_id in matches {
			apply_change_to_entity(state, entity_id, change, event)
		}
		delete(matches)
	}
}

@(private = "file")
apply_change_to_entity :: proc(state: ^State, entity_id: Entity_Id, change: ^Change, event: Trigger) {
	assert(valid_entity(state, entity_id))
	entity := &state.entities[int(entity_id)]
	#partial switch change.kind {
	case .Add_Tag:
		if !has_tag(entity, change.key) {
			add_tag(entity, change.key)
			append(&state.changes, Applied_Change{kind = .Tag_Added, entity = entity_id, key = change.key})
		}
	case .Remove_Tag:
		if has_tag(entity, change.key) {
			remove_tag(entity, change.key)
			append(&state.changes, Applied_Change{kind = .Tag_Removed, entity = entity_id, key = change.key})
		}
	case .Set_Stat:
		before, present := get_stat(entity, change.key)
		if !present || before != change.int_value {
			set_stat(entity, change.key, change.int_value)
			append(
				&state.changes,
				Applied_Change {
					kind = .Stat_Set,
					entity = entity_id,
					key = change.key,
					stat_before = before,
					stat_after = change.int_value,
				},
			)
		}
	case .Inc_Stat:
		before, present := get_stat(entity, change.key)
		after := before + change.int_value
		if !present || before != after {
			set_stat(entity, change.key, after)
			append(
				&state.changes,
				Applied_Change {
					kind = .Stat_Set,
					entity = entity_id,
					key = change.key,
					stat_before = before,
					stat_after = after,
				},
			)
		}
	case .Dec_Stat:
		before, present := get_stat(entity, change.key)
		after := before - change.int_value
		if !present || before != after {
			set_stat(entity, change.key, after)
			append(
				&state.changes,
				Applied_Change {
					kind = .Stat_Set,
					entity = entity_id,
					key = change.key,
					stat_before = before,
					stat_after = after,
				},
			)
		}
	case .Set_Link:
		target, ok := resolve_link_target(state, change.link_target, event)
		if ok {
			before, present := get_link_target(entity, change.key)
			if !present || before != target {
				set_link(entity, change.key, target)
				append(
					&state.changes,
					Applied_Change {
						kind = .Link_Set,
						entity = entity_id,
						key = change.key,
						link_before = before,
						link_after = target,
					},
				)
			}
		}
	case .Remove_Link:
		before, present := get_link_target(entity, change.key)
		if present {
			remove_link(entity, change.key)
			append(
				&state.changes,
				Applied_Change{kind = .Link_Removed, entity = entity_id, key = change.key, link_before = before},
			)
		}
	case .Add_Entity:
		if entity.removed {
			entity.removed = false
			append(&state.changes, Applied_Change{kind = .Entity_Added, entity = entity_id})
		}
	case .Remove_Entity:
		if !entity.removed {
			entity.removed = true
			append(&state.changes, Applied_Change{kind = .Entity_Removed, entity = entity_id})
		}
	case .Remove_Property:
		if has_tag(entity, change.key) {
			remove_tag(entity, change.key)
			append(&state.changes, Applied_Change{kind = .Tag_Removed, entity = entity_id, key = change.key})
		}
		if before, present := get_stat(entity, change.key); present {
			remove_stat(entity, change.key)
			append(
				&state.changes,
				Applied_Change{kind = .Stat_Removed, entity = entity_id, key = change.key, stat_before = before},
			)
		}
		if before, present := get_link_target(entity, change.key); present {
			remove_link(entity, change.key)
			append(
				&state.changes,
				Applied_Change{kind = .Link_Removed, entity = entity_id, key = change.key, link_before = before},
			)
		}
	}
}

@(private = "file")
@(require_results)
resolve_link_target :: proc(state: ^State, target: Link_Target, event: Trigger) -> (Entity_Id, bool) {
	#partial switch target.kind {
	case .Entity:
		return target.entity, valid_entity(state, target.entity)
	case .Trigger:
		return event.entity, event.kind == .Entity && valid_entity(state, event.entity)
	case .Lookup_Entity_Link:
		if !valid_entity(state, target.entity) {
			return INVALID_ENTITY, false
		}
		return get_link_target(&state.entities[int(target.entity)], target.key)
	case .Lookup_Trigger_Link:
		if event.kind != .Entity {
			return INVALID_ENTITY, false
		}
		return get_link_target(&state.entities[int(event.entity)], target.key)
	}
	return INVALID_ENTITY, false
}

@(private = "file")
@(require_results)
valid_entity :: proc(state: ^State, id: Entity_Id) -> bool {
	return id != INVALID_ENTITY && int(id) >= 0 && int(id) < len(state.entities)
}

@(private = "file")
@(require_results)
entity_is_active :: proc(state: ^State, id: Entity_Id) -> bool {
	return valid_entity(state, id) && !state.entities[int(id)].removed
}

@(private = "file")
@(require_results)
has_tag :: proc(entity: ^Entity_State, key: Word_Id) -> bool {
	for tag in entity.tags {
		if tag == key {
			return true
		}
	}
	return false
}

@(private = "file")
add_tag :: proc(entity: ^Entity_State, key: Word_Id) {
	if has_tag(entity, key) {
		return
	}
	append(&entity.tags, key)
}

@(private = "file")
remove_tag :: proc(entity: ^Entity_State, key: Word_Id) {
	for tag, index in entity.tags {
		if tag == key {
			unordered_remove(&entity.tags, index)
			return
		}
	}
}

@(private = "file")
@(require_results)
get_stat :: proc(entity: ^Entity_State, key: Word_Id) -> (i32, bool) {
	for stat in entity.stats {
		if stat.key == key {
			return stat.value, true
		}
	}
	return 0, false
}

@(private = "file")
@(require_results)
get_stat_value :: proc(entity: ^Entity_State, key: Word_Id) -> i32 {
	value, _ := get_stat(entity, key)
	return value
}

@(private = "file")
set_stat :: proc(entity: ^Entity_State, key: Word_Id, value: i32) {
	for &stat in entity.stats {
		if stat.key == key {
			stat.value = value
			return
		}
	}
	append(&entity.stats, Stat{key = key, value = value})
}

@(private = "file")
remove_stat :: proc(entity: ^Entity_State, key: Word_Id) {
	for stat, index in entity.stats {
		if stat.key == key {
			unordered_remove(&entity.stats, index)
			return
		}
	}
}

@(private = "file")
@(require_results)
get_link_target :: proc(entity: ^Entity_State, key: Word_Id) -> (Entity_Id, bool) {
	for link in entity.links {
		if link.key == key {
			return link.target, true
		}
	}
	return INVALID_ENTITY, false
}

@(private = "file")
set_link :: proc(entity: ^Entity_State, key: Word_Id, target: Entity_Id) {
	for &link in entity.links {
		if link.key == key {
			link.target = target
			return
		}
	}
	append(&entity.links, Link{key = key, target = target})
}

@(private = "file")
remove_link :: proc(entity: ^Entity_State, key: Word_Id) {
	for link, index in entity.links {
		if link.key == key {
			unordered_remove(&entity.links, index)
			return
		}
	}
}

@(private = "file")
@(require_results)
compare_i32 :: proc(actual: i32, op: Compare_Op, expected: i32) -> bool {
	#partial switch op {
	case .Eq:
		return actual == expected
	case .Gt:
		return actual > expected
	case .Lt:
		return actual < expected
	}
	return false
}
